import {
	FolderTree,
	Search,
	BookOpenCheck,
	FilePenLine,
	TerminalIcon,
	GlobeIcon,
	ShieldCheck,
	SquareFunction,
	ListTree,
	Component,
	ArrowRightLeft,
	FilePlus2Icon,
	FileMinus2Icon,
	BotIcon,
	AlertCircleIcon,
	CheckCircle2Icon,
	WrenchIcon,
	LucideIcon,
} from "lucide-react"


export const TOOL_ICONS: Record<string, LucideIcon> = {
	readFile: BookOpenCheck,
	read_file: BookOpenCheck,
	readLineRange: BookOpenCheck,
	read_line_range: BookOpenCheck,
	listFilesTopLevel: FolderTree,
	list_files_top_level: FolderTree,
	listFilesRecursive: FolderTree,
	list_files_recursive: FolderTree,
	searchFiles: Search,
	search_files: Search,
	listCodeDefinitionNames: ListTree,
	editFile: FilePenLine,
	edit_file: FilePenLine,
	editedExistingFile: FilePenLine,
	executeCommand: TerminalIcon,
	execute_command: TerminalIcon,
	browser_action: GlobeIcon,
	browser_action_result: GlobeIcon,
	webFetch: GlobeIcon,
	webSearch: GlobeIcon,
	diagnosticsScan: ShieldCheck,
	diagnostics_scan: ShieldCheck,
	getFunction: SquareFunction,
	get_function: SquareFunction,
	getFileSkeleton: ListTree,
	get_file_skeleton: ListTree,
	findSymbolReferences: Component,
	find_symbol_references: Component,
	replaceSymbol: ArrowRightLeft,
	renameSymbol: ArrowRightLeft,
	rename_symbol: ArrowRightLeft,
	newFileCreated: FilePlus2Icon,
	fileDeleted: FileMinus2Icon,
	subagent: BotIcon,
	replace_symbol: ArrowRightLeft,
	error: AlertCircleIcon,
	success: CheckCircle2Icon,

}

export function getIconForTool(toolName: string): LucideIcon {
	return TOOL_ICONS[toolName] || WrenchIcon
}
